#!/usr/bin/env bash
# Policy greps for M07 routing freeze. No op, no curl, no secrets.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DOC="$ROOT/docs/model-routing.md"
SKILL="$ROOT/skills/xbgst/SKILL.md"
SHARED="$ROOT/commands/references/xbreed-shared.md"
AGENT="$ROOT/agents/the-revenger.md"
L2TEST="$ROOT/tests/test-prime-agent-l2.sh"
OPENAI_L2TEST="$ROOT/tests/test-openai-primeagent-routing.sh"
L2WRAP="$ROOT/scripts/prime-agent-l2.sh"
PA="$ROOT/skills/xbgst-primeagent/SKILL.md"

fail() { echo "FAIL: $*" >&2; exit 1; }

need() {
  local file=$1 needle=$2
  [[ -f "$file" ]] || fail "missing $file"
  grep -F -q -- "$needle" "$file" || fail "$file missing '$needle'"
}

need_re() {
  local file=$1 pat=$2
  [[ -f "$file" ]] || fail "missing $file"
  grep -E -q -- "$pat" "$file" || fail "$file missing /$pat/"
}

forbid() {
  local file=$1 needle=$2
  [[ -f "$file" ]] || fail "missing $file"
  if grep -q -- "$needle" "$file"; then
    fail "$file must not contain '$needle'"
  fi
}

echo "→ route-smoke (policy): $ROOT"

[[ -f "$DOC" ]] || fail "missing routing table: $DOC"
[[ -f "$SKILL" ]] || fail "missing skill: $SKILL"
[[ -f "$SHARED" ]] || fail "missing shared ref: $SHARED"
[[ -f "$AGENT" ]] || fail "missing agent: $AGENT"
[[ -x "$L2TEST" || -f "$L2TEST" ]] || fail "missing L2 test: $L2TEST"

# E3 + Token Plan URL + live PASS freeze (no live calls here)
need "$DOC" "DASHSCOPE_API_KEY"
need "$DOC" "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1"
need "$DOC" "M02 PASS HTTP 200"
need "$DOC" "M03 PASS HTTP 200"
need "$DOC" "M04 PASS HTTP 200"
need "$DOC" "qwen3.8-max"
need "$DOC" "XBGST_QWEN38_OK"
need "$DOC" "deepseek-v4-flash-0731"
need "$DOC" "XBGST_DSFLASH0731_OK"
need "$DOC" "deepseek-v4-pro-0813"
need "$DOC" "XBGST_DSPRO0813_OK"
need "$DOC" "gpt-daybreak-blue-latest"
need "$DOC" "XBGST_DAYBREAK_BLUE_OK"
need "$DOC" "Do not alias unversioned"
need "$DOC" "Do not pass \`service_tier\`"
need "$DOC" "lab/defensive"
need "$DOC" "cdx-revenger"
need "$DOC" "Exception E2"
need "$DOC" "model: inherit"
# Daybreak + E2 use stock Codex; Titanium is L3-only
need "$DOC" "codex exec -m gpt-daybreak-blue-latest"
need "$DOC" "sekhmet L3 workers only"
need "$DOC" "L2 substrate must **never** be invoked with Titanium"
if grep -E 'codex-titanium exec -m gpt-daybreak-blue-latest' "$DOC" >/dev/null 2>&1; then
  fail "$DOC must not route Daybreak through codex-titanium"
fi
if grep -E 'codex-titanium exec -m gpt-5.6-luna' "$DOC" >/dev/null 2>&1; then
  fail "$DOC must not route E2 through codex-titanium"
fi

# Probe-gated rows (exact model ids; token-plan / daybreak lab lanes)
need_re "$DOC" 'token-plan[[:space:]]*\|[[:space:]]*qwen3\.8-max'
need_re "$DOC" 'token-plan[[:space:]]*\|[[:space:]]*deepseek-v4-flash-0731'
need_re "$DOC" 'token-plan[[:space:]]*\|[[:space:]]*deepseek-v4-pro-0813'
need_re "$DOC" 'daybreak lab[[:space:]]*\|[[:space:]]*gpt-daybreak-blue-latest'

# Unversioned deepseek must not appear as a model id cell
if grep -E '\|[[:space:]]*deepseek[[:space:]]*\|' "$DOC" >/dev/null 2>&1; then
  fail "$DOC aliases unversioned deepseek"
fi
if grep -E '\|[[:space:]]*deepseek-v4[[:space:]]*\|' "$DOC" >/dev/null 2>&1; then
  fail "$DOC aliases unversioned deepseek-v4"
fi

# Judge stays Grok; Grok-native posture paragraph not rewritten
need "$SKILL" "Judge / xbgst"
need "$SKILL" "runs on **Grok**"
need "$SKILL" "All roles map to Grok. No Claude / Opus / Sonnet / xask / Codex CLI as the default path."
need "$SKILL" "Exception E2"

# E2: the-revenger ROW → cdx (not grok pin)
need_re "$SKILL" '`the-revenger` \(cdx \+ godspeed\)'
need_re "$SKILL" '`the-revenger` \(cdx \+ godspeed\).*\|[[:space:]]*cdx[[:space:]]*\|'
if grep -E '`the-revenger` \(grok \+ godspeed\)' "$SKILL" >/dev/null 2>&1; then
  fail "$SKILL still pins the-revenger row to grok"
fi

# Shared RE row (one line)
need_re "$SHARED" '\| RE \| `the-revenger` \| cdx \|'

# Agent file stays inherit (gx-revenger fallback). Do not edit this file in M07.
need_re "$AGENT" '^model: inherit$'

# E2 footnote: stock codex, not titanium
need "$SKILL" "codex exec -m gpt-5.6-luna"
need "$SKILL" "not \`codex-titanium\`"
need "$SKILL" "Titanium is reserved for sekhmet L3 workers"
need "$PA" "Never exec \`codex-titanium\`"

# L2 wrapper must never name titanium as an exec target
if grep -E 'codex-titanium' "$L2WRAP" >/dev/null 2>&1; then
  fail "$L2WRAP must not invoke codex-titanium"
fi

# This smoke must stay policy-only (no live secret surfaces)
if grep -E '^[^#]*\bop[[:space:]]+run\b|^[^#]*\bcurl[[:space:]]' "$0" >/dev/null 2>&1; then
  fail "route-smoke.sh must not call op/curl"
fi

echo "OK  routing policy greps"

echo "→ route-smoke (E1): $L2TEST"
bash "$L2TEST"

echo "→ route-smoke (OpenAI L2 route): $OPENAI_L2TEST"
bash "$OPENAI_L2TEST"

echo "PASS: route-smoke policy greps + prime-agent-l2 + OpenAI optional routing"
