#!/usr/bin/env bash
# Freeze / check grok-orch inventory against the Phase 0 host fixture.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FIXTURE_REL="plugins/xbgst-stack/HOST-ORCH-INVENTORY.txt"
FIXTURE="$ROOT/$FIXTURE_REL"
HOST_GROK="${GROK_HOME:-$HOME/.grok}"

# Frozen required names (plan-phase0 Host orch inventory).
SKILLS="xbgst xbgst-livepatch the-janitor godspeed wwkd"
SSOT_FILES="ssot/godspeed-core/directive.md ssot/godspeed-core/filter.md ssot/godspeed-core/velocity.md"
COMMANDS="xbgst.md xbgst-livepatch.md xgs.md xbreed-team.md xbgst-orch.md xbgst-clone.md references/xbreed-shared.md"
AGENTS="connector critic distiller executor labrat mutation-tester reviewer scout scribe sentinel simplifier the-planner the-revenger the-janitor the-musketeer explore general-purpose"
LIVEPATCH="livepatch/patches/0001-ban-generic-subagents.patch livepatch/scripts/check-and-patch.sh scripts/install-host.sh"
BANNED="heuer-planning the-kimiraikkoner"

usage() {
  cat <<'EOF'
Usage:
  orch-inventory.sh --write-host-fixture
  orch-inventory.sh --expect-fixture --home <GROK_HOME> --plugin <plugin-dir>
  orch-inventory.sh --help

--write-host-fixture
  Verify host ~/.grok (or GROK_HOME) has required skills/agents/commands/ssot,
  then write plugins/xbgst-stack/HOST-ORCH-INVENTORY.txt (frozen name list).
  Host dirt the-kimiraikkoner must NOT appear in the fixture.

--expect-fixture --home <GROK_HOME> --plugin <plugin-dir>
  Exit 0 and print "OK inventory match" iff home has required names
  (skills dirs; command files; agent md via GROK_HOME/agents or plugin agents;
  ssot files). Fail if heuer-planning or the-kimiraikkoner are under home
  skills/agents.
EOF
}

die() { echo "FAIL: $*" >&2; exit 1; }

skill_present() {
  local home="$1" name="$2"
  [[ -d "$home/skills/$name" ]] || [[ -L "$home/skills/$name" ]]
}

agent_present() {
  local home="$1" plugin="$2" name="$3"
  [[ -f "$home/agents/${name}.md" ]] || [[ -L "$home/agents/${name}.md" ]] \
    || [[ -f "$plugin/agents/${name}.md" ]]
}

command_present() {
  local home="$1" name="$2"
  [[ -f "$home/commands/$name" ]] || [[ -L "$home/commands/$name" ]]
}

ssot_present() {
  local home="$1" rel="$2"
  [[ -f "$home/$rel" ]] || [[ -L "$home/$rel" ]]
}

banned_present() {
  local home="$1" name="$2"
  [[ -e "$home/skills/$name" ]] || [[ -e "$home/agents/${name}.md" ]] \
    || [[ -d "$home/agents/$name" ]] || [[ -d "$home/skills/$name" ]]
}

verify_host_required() {
  local home="$1"
  local missing=0
  local n

  for n in $SKILLS; do
    skill_present "$home" "$n" || { echo "missing skill: $n" >&2; missing=1; }
  done
  for n in $AGENTS; do
    [[ -f "$home/agents/${n}.md" ]] || [[ -L "$home/agents/${n}.md" ]] \
      || { echo "missing agent: $n.md" >&2; missing=1; }
  done
  for n in $COMMANDS; do
    command_present "$home" "$n" || { echo "missing command: $n" >&2; missing=1; }
  done
  for n in $SSOT_FILES; do
    ssot_present "$home" "$n" || { echo "missing ssot: $n" >&2; missing=1; }
  done
  [[ "$missing" -eq 0 ]] || die "host orch inventory incomplete at $home"
}

write_fixture() {
  verify_host_required "$HOST_GROK"
  mkdir -p "$(dirname "$FIXTURE")"
  {
    echo "# HOST-ORCH-INVENTORY — frozen grok-orch surface (Phase 0 / M01)"
    echo "# Source: plan-phase0 Host orch inventory (required names)"
    echo "# Host dirt excluded: the-kimiraikkoner heuer-planning the-librarian ds4cc"
    echo "# Generated by scripts/orch-inventory.sh --write-host-fixture"
    echo
    echo "[skills]"
    for n in $SKILLS; do echo "$n"; done
    echo
    echo "[ssot]"
    for n in $SSOT_FILES; do echo "$n"; done
    echo
    echo "[commands]"
    for n in $COMMANDS; do echo "$n"; done
    echo
    echo "[agents]"
    for n in $AGENTS; do echo "$n"; done
    echo
    echo "[livepatch]"
    for n in $LIVEPATCH; do echo "$n"; done
    echo
    echo "[banned]"
    for n in $BANNED; do echo "$n"; done
  } >"$FIXTURE"
  # Safety: kimiraikkoner must never land in fixture
  if grep -q 'kimiraikkoner\|heuer-planning\|the-librarian' "$FIXTURE"; then
    # banned section lists heuer/kimiraikkoner by design — only fail if under required sections
    if awk '
      /^\[(skills|ssot|commands|agents|livepatch)\]$/ { sec=1; next }
      /^\[/ { sec=0 }
      sec && /(kimiraikkoner|heuer-planning|the-librarian)/ { found=1 }
      END { exit found ? 0 : 1 }
    ' "$FIXTURE"; then
      die "fixture must not list kimiraikkoner/heuer/librarian under required sections"
    fi
  fi
  echo "Wrote $FIXTURE_REL"
  echo "Verified host required names under $HOST_GROK (kimiraikkoner excluded from fixture)"
}

expect_fixture() {
  local home="" plugin=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --home) home="${2:-}"; shift 2 ;;
      --plugin) plugin="${2:-}"; shift 2 ;;
      *) die "unexpected arg for --expect-fixture: $1" ;;
    esac
  done
  [[ -n "$home" ]] || die "--expect-fixture requires --home"
  [[ -n "$plugin" ]] || die "--expect-fixture requires --plugin"
  [[ -d "$home" ]] || die "home not a directory: $home"
  [[ -d "$plugin" ]] || die "plugin not a directory: $plugin"
  [[ -f "$FIXTURE" ]] || die "missing fixture $FIXTURE_REL (run --write-host-fixture first)"

  local n missing=0
  for n in $SKILLS; do
    skill_present "$home" "$n" || { echo "missing skill: $n" >&2; missing=1; }
  done
  for n in $AGENTS; do
    agent_present "$home" "$plugin" "$n" || { echo "missing agent: $n" >&2; missing=1; }
  done
  for n in $COMMANDS; do
    command_present "$home" "$n" || { echo "missing command: $n" >&2; missing=1; }
  done
  for n in $SSOT_FILES; do
    ssot_present "$home" "$n" || { echo "missing ssot: $n" >&2; missing=1; }
  done
  for n in $BANNED; do
    if banned_present "$home" "$n"; then
      echo "banned present under home: $n" >&2
      missing=1
    fi
  done
  [[ "$missing" -eq 0 ]] || die "inventory mismatch for home=$home plugin=$plugin"
  echo "OK inventory match"
}

MODE=""
EXPECT_ARGS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --help|-h) usage; exit 0 ;;
    --write-host-fixture) MODE=write; shift ;;
    --expect-fixture) MODE=expect; shift; EXPECT_ARGS=("$@"); break ;;
    *) usage >&2; die "unknown option: $1" ;;
  esac
done

case "${MODE:-}" in
  write) write_fixture ;;
  expect) expect_fixture "${EXPECT_ARGS[@]}" ;;
  *) usage >&2; die "specify --write-host-fixture, --expect-fixture, or --help" ;;
esac
